
The following have been reloaded with a version change:
  1) gcc/10.2.0 => gcc/13.0.1

Traceback (most recent call last):
  File "/burg/ccce/users/eav2136/projects/interpolation/01_get_bands/c_df_dft_mp2.py", line 46, in <module>
    mo_energy, mo_coeff = mymf.get_bands(kpts)
  File "/burg/berkelbach/users/eav2136/builds/pyscf/projected-cvs/pyscf/pyscf/pbc/scf/khf.py", line 716, in get_bands
    fock = fock + self.get_veff(cell, dm_kpts, kpts=kpts, kpts_band=kpts_band)
  File "/burg/berkelbach/users/eav2136/builds/pyscf/projected-cvs/pyscf/pyscf/pbc/dft/krks.py", line 97, in get_veff
    vxc += vj
numpy.core._exceptions._UFuncOutputCastingError: Cannot cast ufunc 'add' output from dtype('complex128') to dtype('float64') with casting rule 'same_kind'
