
The following have been reloaded with a version change:
  1) gcc/10.2.0 => gcc/13.0.1

/burg/berkelbach/users/eav2136/builds/pyscf/projected-cvs/pyscf/pyscf/pbc/tools/lattice.py:137: UserWarning: Use ase.build.bulk() instead
  ase_atom = bulk('LiF', 'rocksalt', a=4.0351*A2B)
WARNING!
  Very diffused basis functions are found in the basis set. They may lead to severe
  linear dependence and numerical instability.  You can set  cell.exp_to_discard=0.1
  to remove the diffused Gaussians whose exponents are less than 0.1.

Traceback (most recent call last):
  File "/burg/ccce/users/eav2136/projects/interpolation/01_get_bands/lif_df_dft_mp2.py", line 53, in <module>
    mydf.build()
  File "/burg/berkelbach/users/eav2136/builds/pyscf/projected-cvs/pyscf/pyscf/pbc/df/df.py", line 595, in build
    self._make_j3c(self.cell, self.auxcell, kptij_lst, cderi)
  File "/burg/berkelbach/users/eav2136/builds/pyscf/projected-cvs/pyscf/pyscf/pbc/df/df.py", line 413, in _make_j3c
    make_kpt(uniq_kptji_id, cholesky_j2c)
  File "/burg/berkelbach/users/eav2136/builds/pyscf/projected-cvs/pyscf/pyscf/pbc/df/df.py", line 363, in make_kpt
    feri['j3c/%d/%d'%(ji,istep)] = v
  File "/burg/berkelbach/users/eav2136/builds/spack/develop/spack/var/spack/environments/pyscf/.spack-env/view/lib/python3.10/site-packages/h5py/_hl/group.py", line 483, in __setitem__
    ds = self.create_dataset(None, data=obj)
  File "/burg/berkelbach/users/eav2136/builds/spack/develop/spack/var/spack/environments/pyscf/.spack-env/view/lib/python3.10/site-packages/h5py/_hl/group.py", line 183, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
  File "/burg/berkelbach/users/eav2136/builds/spack/develop/spack/var/spack/environments/pyscf/.spack-env/view/lib/python3.10/site-packages/h5py/_hl/dataset.py", line 168, in make_new_dset
    dset_id.write(h5s.ALL, h5s.ALL, data)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 280, in h5py.h5d.DatasetID.write
  File "h5py/_proxy.pyx", line 114, in h5py._proxy.dset_rw
OSError: [Errno 122] Can't synchronously write data (file write failed: time = Fri Dec 15 08:04:31 2023
, filename = '/burg/ccce/users/eav2136/projects/interpolation/01_get_bands/tmp/tmpyp4nvv17', file descriptor = 6, errno = 122, error message = 'Disk quota exceeded', buf = 0x102521f0, total write size = 1427712, bytes this sub-write = 1427712, bytes actually written = 18446744073709551615, offset = 0)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 201, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Disable slist on flush dest failure failed (file write failed: time = Fri Dec 15 08:04:32 2023
, filename = '/burg/ccce/users/eav2136/projects/interpolation/01_get_bands/tmp/tmpyp4nvv17', file descriptor = 6, errno = 122, error message = 'Disk quota exceeded', buf = 0xd926b18, total write size = 360448, bytes this sub-write = 360448, bytes actually written = 18446744073709551615, offset = 0)
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 201, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Disable slist on flush dest failure failed (file write failed: time = Fri Dec 15 08:04:32 2023
, filename = '/burg/ccce/users/eav2136/projects/interpolation/01_get_bands/tmp/tmpyp4nvv17', file descriptor = 6, errno = 122, error message = 'Disk quota exceeded', buf = 0xd926b18, total write size = 360448, bytes this sub-write = 360448, bytes actually written = 18446744073709551615, offset = 0)
/cm/local/apps/slurm/var/spool/job10633663/slurm_script: line 21: 3274447 Killed                  python lif_df_dft_mp2.py $1 $2 $3
slurmstepd: error: Detected 1 oom-kill event(s) in step 10633663.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
