
The following have been reloaded with a version change:
  1) gcc/10.2.0 => gcc/13.0.1

/burg/berkelbach/users/eav2136/builds/pyscf/projected-cvs/pyscf/pyscf/pbc/tools/lattice.py:137: UserWarning: Use ase.build.bulk() instead
  ase_atom = bulk('LiF', 'rocksalt', a=4.0351*A2B)
WARNING!
  Very diffused basis functions are found in the basis set. They may lead to severe
  linear dependence and numerical instability.  You can set  cell.exp_to_discard=0.1
  to remove the diffused Gaussians whose exponents are less than 0.1.

Traceback (most recent call last):
  File "/burg/berkelbach/users/eav2136/projects/interpolation/01_get_bands/lif_df_dft_mp2.py", line 48, in <module>
    mo_energy, mo_coeff = mymf.get_bands(kpts)
  File "/burg/berkelbach/users/eav2136/builds/pyscf/projected-cvs/pyscf/pyscf/pbc/scf/khf.py", line 716, in get_bands
    fock = fock + self.get_veff(cell, dm_kpts, kpts=kpts, kpts_band=kpts_band)
  File "/burg/berkelbach/users/eav2136/builds/pyscf/projected-cvs/pyscf/pyscf/pbc/dft/krks.py", line 89, in get_veff
    n, exc, vxc = ks._numint.nr_rks(cell, ks.grids, ks.xc, dm, 0,
  File "/burg/berkelbach/users/eav2136/builds/pyscf/projected-cvs/pyscf/pyscf/pbc/dft/numint.py", line 1134, in nr_rks
    return nr_rks(self, cell, grids, xc_code, dms, 0, 0,
  File "/burg/berkelbach/users/eav2136/builds/pyscf/projected-cvs/pyscf/pyscf/pbc/dft/numint.py", line 344, in nr_rks
    for ao_k1, ao_k2, mask, weight, coords \
  File "/burg/berkelbach/users/eav2136/builds/pyscf/projected-cvs/pyscf/pyscf/pbc/dft/numint.py", line 1207, in block_loop
    ao_k1 = self.eval_ao(cell, coords, kpts_band, deriv=deriv, non0tab=non0)
  File "/burg/berkelbach/users/eav2136/builds/pyscf/projected-cvs/pyscf/pyscf/pbc/dft/numint.py", line 1070, in eval_ao
    return eval_ao_kpts(cell, coords, kpts, deriv,
  File "/burg/berkelbach/users/eav2136/builds/pyscf/projected-cvs/pyscf/pyscf/pbc/dft/numint.py", line 91, in eval_ao_kpts
    return cell.pbc_eval_gto(feval, coords, comp, kpts,
  File "/burg/berkelbach/users/eav2136/builds/pyscf/projected-cvs/pyscf/pyscf/pbc/gto/cell.py", line 1645, in pbc_eval_gto
    return pbc_eval_gto(self, eval_name, coords, comp, kpts, kpt,
  File "/burg/berkelbach/users/eav2136/builds/pyscf/projected-cvs/pyscf/pyscf/pbc/gto/eval_gto.py", line 125, in eval_gto
    out = numpy.empty((nkpts,comp,nao,ngrids), dtype=numpy.complex128)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 116. GiB for an array with shape (1000, 4, 26, 75088) and data type complex128
